### PR TITLE
Johann profile

### PR DESCRIPTION
**Pull request by JohannBillar**
This PR is under 🚧  Hold off on merging. 
/profile 
/profile/:uid

  - Created an action and reducer that loads all the app users from firebase and adds any new ones
  - Created a app-users container and component to render all the users. 

  - NEXT 
    - Build the UI for profile index
    - Build UI for profile details
    - Build the EDIT form

### CODE REVIEW

**Comment by omarcodex** [comment]
Awesome! I'll hold off, looking forward to following this thread.

**Comment by JohannBillar** [comment]
@omarcodex You can see what I have so far at https://mydowhop.com/my-profile. Click on any of the users and you'll go to the profile details page. If it's your profile you can edit.  

I'm using react-router. The problem I'm running into is when I try to deep link to e.g. https://mydowhop.com/my-profile/VYw0lPDFD3btHJadneuSFGjy8wk1 the servers serves up index.html/ instead of my-profile.html. The behavior is correct for SPAs where this works. Not sure what to do about this.

**Comment by JohannBillar** [comment]
@omarcodex and @DoTinkerDo/tinkerdos I'm using a combination of react-router and URL search params in order to let us  "fake" deep linking to dynamic URLs. 

I had to go this 'route' as URLs that we type into the browser re-route to /index.hmtl and not /my-profile.html. This is what we tell the server to do because the rest of our app lives there. 

The solution was: instead of  /my-profile/:uid we're doing /my-profile?uid) and then grabbing the location.search param instead of the router match.params. I build an profile index page which we can link to from within the react app but not from outside the app because it would live at:
e.g. /my-profile/index and the server would send us to index...

@omarcodex I'm open to suggestions on how to make this more robust.

**Comment by JohannBillar** [comment]
:shipit:

**Pull request merged**
