### PR TITLE
Omar linking whos

### PR DESCRIPTION
**Pull request by omarcodex**
The goal of this feature is to create user icons that are clickable from the DoWhop View panel. At the moment, it works as intended if users click the main selector block or 'View' tab, or double-click a smaller selector block.

Hold off on merge -- trying to fix bug first >_< (update: we will return to issue)

### CODE REVIEW

**Comment by JohannBillar** [comment]
@omarcodex Do you still want to hold of merging or can I deploy a Beta? :shipit: ?

**Comment by omarcodex** [comment]
@JohannBillar yeah, I think we should deploy Beta - with the knowledge that we should refactor timings in the future 🐞

**Comment by JohannBillar** [comment]
@omarcodex Great job getting this feature this far! It appears that we've reached Callback Hell. :( We can pair on this when we're both at Evo and see if we can refactor in order to get the doers/creators in sync with the view.

**Comment by omarcodex** [comment]
@JohannBillar sounds good! Would be great to follow through on callbacks. Thinking if better to pinpoint the timings or throw more data into the fb sessions?

**Comment by JohannBillar** [comment]
🤖  Launching this code to Firebase!

**Pull request merged**
