### PR TITLE
Omar update welcome message for new users

### PR DESCRIPTION
**Pull request by omarcodex**
* Added create welcome message function to create form and create-la form that fixes previous 'undefined' issue.

* Copy for new Default DoWhops reads:

>> "Hi FirstName, welcome to DoWhop! My name is Casey and I will be your personal DoWhop assistant. Is there anything I can help you do?"

Appears OK to merge.

### CODE REVIEW

**Comment by JohannBillar** [comment]
@omarcodex sounds good.

**Comment by omarcodex** [comment]
@johann this appears to work as expected! Would you be able to add `createDoWhopWelcomeMessage(doWhopDescriptionData)` to admin or would you like me to do it?

**Comment by omarcodex** [comment]
Update: I've added the new function call to the create-form-la -- not sure how best to test it. :S

**Comment by JohannBillar** [comment]
Looking good!

**Pull request merged**
